### PR TITLE
Remove PhEDEx/Dynamo replica requests from Unified modules

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes https://github.com/dmwm/WMCore/issues/9836

#### Status
In development

#### Description
Bare minimum changes to stop making PhEDEx requests to subscribe data.
Bare minimum changes to stop making Dynamo/DDM data placement requests.

Note that the code needs to be properly cleaned up such that CPU cycles are not spent on handling data that won't be subscribed.

#### Is it backward compatible (if not, which system it affects?)
no

#### Related PRs
none

#### External dependencies / deployment changes
none

#### Mention people to look at PRs
@haozturk @z4027163

### CODE REVIEW

**Comment by haozturk** [comment]
Hi @amaltaro do you think we should make this PR to master? I was thinking that we are planning to aggregate all phedex changes in a branch other than master, then run the modules manually on some testing workflows to see how modules behave after the changes. Please let me know what you think. Thanks!

**Comment by amaltaro** [comment]
If you are planning to:
* run modules on a specific workflow
* and only run modules manually

then I think you could test these changes from master. There is no need to merge it, you can either checkout this branch, or patch a testing unified installation with something like:
```
curl https://patch-diff.githubusercontent.com/raw/CMSCompOps/WmAgentScripts/pull/653.patch | patch -p 1
```

**Comment by haozturk** [comment]
Hi @amaltaro , we have run the `checkor` module of this version for the following workflow when it was in `completed` state: https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_task_HIG-RunIIFall17wmLHEGS-05036__v1_T_200712_005621_4159
It did not run successfully with this version. It has run successfully when we deleted the following code pieces:
1. https://github.com/amaltaro/WmAgentScripts/blob/wmcore-9836/Unified/checkor.py#L1002-L1008
2. https://github.com/amaltaro/WmAgentScripts/blob/wmcore-9836/Unified/checkor.py#L1356
3. https://github.com/amaltaro/WmAgentScripts/blob/wmcore-9836/Unified/checkor.py#L1360

After we remove/comment out these 3 code pieces, it successfully made the state transition from `completed` to `closed-out`.

Afterwards we have run the `closor` module, but it's failed due to NoParentageResolved issue, therefore could not make the `closed-out` to `announced` transition. I remember that you've solved this issue recently. Why do you think it happened?
```
Delayed announcement of cmsunified_task_HIG-RunIIFall17wmLHEGS-05036__v1_T_200712_005621_4159 due to unresolved Parentage dependencies
[True, 'No ParentageResolved']
Error with cmsunified_task_HIG-RunIIFall17wmLHEGS-05036__v1_T_200712_005621_4159 to be announced 
[true, "No ParentageResolved"]
```
Please see the full logs below:

[checkor_log.txt](https://github.com/CMSCompOps/WmAgentScripts/files/5247617/checkor_log.txt)
[closor_log.txt](https://github.com/CMSCompOps/WmAgentScripts/files/5247618/closor_log.txt)

**Comment by haozturk** [comment]
Also note that, `collector` and `spreador` modules are no longer run by Unified, so we do not have to test those. Additionally, `subscribor` module is all about making output subscriptions and it will be removed completely in this transition. That's why we thought that the best test would be not to run it. After solving the `NoParentageResolved` issue for the `closor`, we also need to test the `GQ` module. I guess it is all about Resubmissions/ACDCs, so we may need to find an ACDC workflow to test this one.

**Comment by amaltaro** [comment]
Hasan, thanks for testing it and proposing further changes. You can find your 3 blocks of code removed in the 3rd commit.

About `collector` and `spreador`, who runs them then? Or is it supposed to be an standalone script?

About `GQ`, I think we should deprecate it and make sure a GH issue gets created in WMCore such that we can try to provide a similar functionality - if possible - (I believe it's rebalancing input data according to site load and/or bad transfers...).

I'm looking at the workflow you used for these tests and will make its output data placement through MSOutput.

**Comment by amaltaro** [comment]
About the workflow parentage, our daemon runs once every 3 hours, so by now it's probably already fixed.

For the record, I enabled MSOutput for your workflow only and here's the final record (a non-custodial DDM request, and a tape custodial PhEDEx request):
```
2020-09-18 22:38:37,218:DEBUG:MSOutput: {u'Campaign': u'RunIIFall17wmLHEGS',
 u'CreationTime': 1600461222,
 u'IsRelVal': False,
 u'LastUpdate': 1600461517,
 u'OutputDatasets': [u'/GluGluToRadionToHHTo2G2l2nu_M-850_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/MINIAODSIM'],
 u'OutputMap': [{u'Campaign': u'RunIIFall17MiniAODv2',
                 u'Copies': 1,
                 u'Dataset': u'/GluGluToRadionToHHTo2G2l2nu_M-850_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2/MINIAODSIM',
                 u'DatasetSize': 13091055108L,
                 u'DiskDestination': u'(tier=2|tier=1)&cms_type=real&rse_type=DISK',
                 u'DiskRuleID': u'48147',
                 u'TapeDestination': u'T0_CH_CERN_MSS',
                 u'TapeRuleID': u'2410882'}],
 u'RequestName': u'cmsunified_task_HIG-RunIIFall17wmLHEGS-05036__v1_T_200712_005621_4159',
 u'RequestType': u'StepChain',
 u'TransferStatus': u'done',
 u'_id': u'cmsunified_task_HIG-RunIIFall17wmLHEGS-05036__v1_T_200712_005621_4159'}
```

**Comment by haozturk** [comment]
Hi @amaltaro Thanks for applying necessary changes. I've run the `closor` module again and it successfully made the `closed-out` to `announced` transition. So, in this stage, we can say that `checkor` and `closor` modules are good to go with these changes.

About `spreador` and `collector`, I have not found any logs produced from these modules. So, I am pretty sure that they haven't been used in Unified machinery for a long time. Even if they are standalone modules, Sharad did not told me any use case of it. Qier also does not know any use of these ones. Therefore, I think we should not worry about these modules. @z4027163 Can you please confirm?

About `GQ`, your suggestion of deprecating it in Unified and implementing in WMCore sounds good to me. Let me examine this module and its logs a little bit to see if what it does exactly. @z4027163 What do you think about this module? For the sake of this PR, I think we should also test it somehow. I am working on it. 

And also thanks for enabling MSOutput for this test workflow. It's announced and its output data placement is done, so we are safe.

Let me add the log of the closor module for the record.
[closor_log_v2.txt](https://github.com/CMSCompOps/WmAgentScripts/files/5250491/closor_log_v2.txt)

**Comment by haozturk** [comment]
Hi @amaltaro I examined the `GQ` module more deeply. In terms of Phedex transfer request, it checks the input locations and sitewhitelist by considering the `NoInputUpdate` and `NoPileupUpdate` parameters of the workqueue element. If there is no overlap between the sitewhitelist and input location, it makes a transfer request. Normally, MSTransferor should deal with such concerns, right?  

Hence, this module has nothing to do with output data placement. If we merge this PR, the functionality that I described will be removed. Considering the role of Unified and WMCore, I think that Unified should not make such requests in the future. Maybe what we can do is to revise this module such that it only creates warnings to us in such cases without touching anything. Then we can evaluate these warnings to improve our assignment logic or WMCore's input data placement logic. What do you think @amaltaro @z4027163 ?

Here is an example from the logs:
```
pdmvserv_task_EXO-RunIIFall17NanoAODv6-03546__v1_T_200609_093751_6901

Block /WPhi_2e_M-40_PS_TuneCP5_madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM#cc93afb6-d470-49fc-931b-efef01990e52 is at T1_US_FNAL_Buffer,T1_US_FNAL_MSS,T2_US_Florida,T2_US_Nebraska while asked to run at T1_DE_KIT_Disk,T1_ES_PIC_Disk,T1_FR_CCIN2P3_Disk,T1_IT_CNAF_Disk,T1_RU_JINR_Disk,T1_UK_RAL_Disk,T1_US_FNAL_Disk,T2_BE_IIHE,T2_BE_UCL,T2_CH_CERN,T2_CH_CERNBOX,T2_CH_CSCS,T2_CN_Beijing,T2_DE_DESY,T2_DE_RWTH,T2_ES_CIEMAT,T2_ES_IFCA,T2_FR_CCIN2P3,T2_FR_GRIF_IRFU,T2_FR_GRIF_LLR,T2_FR_IPHC,T2_IT_Bari,T2_IT_Legnaro,T2_IT_Rome,T2_PL_Swierk,T2_PT_NCG_Lisbon,T2_RU_JINR,T2_UA_KIPT,T2_UK_London_Brunel,T2_UK_London_IC,T2_UK_SGrid_RALPP,T2_US_Caltech,T2_US_MIT,T2_US_Purdue,T2_US_UCSD,T2_US_Vanderbilt,T2_US_Wisconsin,T3_US_FNALLPC,T3_US_Vanderbilt_EC2
The following blocks/files need to be put back on disk
/WPhi_2e_M-40_PS_TuneCP5_madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM#cc93afb6-d470-49fc-931b-efef01990e52



pdmvserv_task_EXO-RunIIFall17NanoAODv6-03546__v1_T_200609_093751_6901 has problematic blocks
        /WPhi_2e_M-40_PS_TuneCP5_madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM#cc93afb6-d470-49fc-931b-efef01990e52 in element f8d548febc8adc579f254e0312eac637
        should be replicated to T1_ES_PIC,T2_CH_CERN,T2_FR_CCIN2P3,T2_IT_Rome,T1_US_FNAL,T0_CH_CSCS_HPC,T2_DE_RWTH,T2_FR_GRIF_IRFU,T1_FR_CCIN2P3,T1_IT_CNAF,T2_US_Purdue,T1_RU_JINR,T2_UK_SGrid_RALPP,T2_FR_GRIF_IRFU,T2_UK_London_IC,T2_BE_UCL,T2_ES_IFCA,T2[eos-cp] copied 1/1 files and 9044 B in 0.22 seconds with 41.25 kB/s
[eos-cp] copied 1/1 files and 608.20 kB in 4.65 seconds with 130.86 kB/s
_IT_Legnaro,T2_IT_Bari,T2_CN_Beijing,T2_ES_CIEMAT,T2_FR_IPHC,T2_US_Vanderbilt,T2_UA_KIPT,T2_DE_DESY,T2_US_MIT,T2_BE_IIHE,T2_US_Caltech,T1_DE_KIT,T2_US_UCSD,T2_UK_London_Brunel,T2_CH_CERN,T2_PT_NCG_Lisbon,T2_RU_JINR,T2_PL_Swierk,T2_US_Vanderbilt,T2_US_Wisconsin,T1_UK_RAL,T1_US_FNAL
replacing /WPhi_2e_M-40_PS_TuneCP5_madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM#cc93afb6-d470-49fc-931b-efef01990e52 at T1_US_FNAL_Disk
{u'phedex': {u'request_created': [{u'id': u'2410435'}], u'request_date': u'2020-09-18 12:08:36 UTC', u'request_timestamp': 1600430916.46736, u'call_time': 0.06575, u'instance': u'prod', u'request_call': u'subscribe', u'request_url': u'http://cmsweb.cern.ch:7001/phedex/datasvc/json/prod/subscribe', u'request_version': u'2.5.0pre3-comp'}}

```

**Comment by amaltaro** [comment]
Hasan, I think we can implement something similar in WMCore. Finding the best location for a stuck block at global workqueue level isn't ideal, but I guess some use cases can be implemented. Keep in mind this won't be implemented in the next month or so (neither it is crucial to central production).

**Pull request merged**
