### PR TITLE
Updating the UL18FS campaign adding a pileup file

### PR DESCRIPTION
**Pull request by scarletnorberg**
Updating https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-191 added a pileup file HINPbPbWinter16wmLHEGSHIMix
Turned a campaign to true https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-192 the RunIISpring21UL18FSGSPremix

### CODE REVIEW

**Comment by haozturk** [comment]
@scarletnorberg  please fix the typo in the site name and also the indendation

**Comment by scarletnorberg** [comment]
Do I need to add disk to the end? What is wrong with indention I thought that did not really matter is it just that you would prefer me to shift it over?

**Comment by haozturk** [comment]
You do not have to add disk at the end. Check the mappings from: http://cms-cric.cern.ch/api/cms/site/query/?json&preset=data-processing

Indendation is important to make it readable. Not important for the machine, but important for the reviewer. I'd prefer you to update the indendation.

**Comment by scarletnorberg** [comment]
Also ok I agree that indention can make it look weird. Let me know if this is better.

**Comment by scarletnorberg** [comment]
Also two pilots finished successfully
https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-175 RunIISummer20UL16MiniAODv2
https://its.cern.ch/jira/projects/PRCAMPAIGNS/issues/PRCAMPAIGNS-176 RunIISummer20UL16MiniAODAPVv2

**Pull request merged**
