### PR TITLE
Initial reqmgr2 assignment patch for RelVals

### PR DESCRIPTION
**Pull request by amaltaro**
@AndrewLevin this should fix the assignment and retrieve of workflows/spec, it's not tested :)
You still need changes for reqMgrClient.py suggested by Seangchan in #129 to make the assignment work.

### CODE REVIEW

**Comment by AndrewLevin** [comment]
hi alan, thanks

please reject this pull request

I have made the necessary changes locally

**Comment by amaltaro** [comment]
Then make a new PR with these necessary changes and we can close this one.

**Comment by vlimant** [comment]
@AndrewLevin is that still relevant ?

**Comment by AndrewLevin** [comment]
You can close the pull request.

I have locally all of the changes I need to use reqmgr2.

I will make a new pull request at some point.

**Pull request closed without merging**
