### PR TITLE
Closing blocks when requested for processing

### PR DESCRIPTION
**Pull request by vlimant**
instead of having opened blocks in phedex dangling around

### CODE REVIEW

**Comment by vlimant** [comment]
@amaltaro tell me if you see any drawbacks to this

**Comment by amaltaro** [comment]
Yes and it should not be forced this way. DBS injection depends on the PhEDEx blocks to be closed, PhEDExInjector is not checking if a block is closed or not, but it's actually closing blocks after some requirements are matched. In short, this won't speed up anything.

The correct way to get this done is to fix that issue in WMCore
https://github.com/dmwm/WMCore/issues/8148

**Comment by vlimant** [comment]
yes to making this more resilient in wmcore.
merging since there is no otherwise drawbacks

**Comment by amaltaro** [comment]
Are you sure that a block not completed (without a complete replica somewhere) is the same as a block being still open?

**Comment by amaltaro** [comment]
BTW, if you want to avoid issues with this. It's better to check whether those blocks opened in PhEDEx are also present (and closed in DBS). If they are not, then you might be closing things before it's supposed to.

Another question, do you record which blocks go through this Unified update? Might be useful for any future debugging.

**Comment by vlimant** [comment]
there's no record ; if people say how they want this, it can be added.

**Pull request merged**
