### PR TITLE
Creating JIRA from unified

### PR DESCRIPTION
**Pull request by vlimant**
not to be merged yet.
this is the branch that can be worked on to create JIRA from unified.

### CODE REVIEW

**Comment by vlimant** [comment]
extending to closor as per #359

**Comment by sharad1126** [comment]
@phylsix you can follow this to start the jira creation. @dabercro FYI

**Comment by vlimant** [comment]
tested with https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-03011 , which created https://its.cern.ch/jira/browse/CMSCOMPPR-4560

**Comment by sharad1126** [comment]
@vlimant this is great. @phylsix @dabercro FYI

**Comment by vlimant** [comment]
one last with
Unified/checkor.py --no_report pdmvserv_task_HIG-RunIIFall18wmLHEGS-00462__v1_T_181120_163346_7091

looks all OK to me

**Comment by dabercro** [comment]
@vlimant, I have a question which should help @phylsix. What should the Operations Support ticket look like? @phylsix will be working on the "Steps to Automating CSP shifting" projects under here: https://twiki.cern.ch/twiki/bin/viewauth/CMS/CompOpsPROperationSupport#Steps_to_Automating_CSP_shifting, and we were thinking the first thing he can do is add some flexibility to the ticket creation.

**Comment by sharad1126** [comment]
@dabercro the ticket creation thing has actually started now with the updates @vlimant did recently. Thanks @vlimant

**Pull request merged**
