### PR TITLE
Remove legacy dashssb

### LINKED ISSUE #487: remove legacy code/links decommissioned
**Impact of the bug**
check function call in unified production instance 

**Describe the bug**
dashb-cms* links were decommissioned in July 2018. https://its.cern.ch/jira/browse/CMSMONIT-124?focusedCommentId=2813499&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2813499. Still exists in the code. 

**How to reproduce it**
Code exists in unified modules. 

**Expected behavior**
should have been removed from code. 

**Additional context and error message**
```
[sagarwal@vocms0275 WmAgentScripts]$ grep -rn 'http://dashb' *
Unified/htmlor.py:156:            text+=', <a href="http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#table=Jobs&date1=%s&date2=%s&sortby=site&task=wmagent_%s"> 1m</a>'%( date1, date2, wfn )
Unified/htmlor.py:158:            text+=', <a href="http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#table=Jobs&date1=%s&date2=%s&sortby=site&task=wmagent_%s"> 1w</a>'%( date1, date2, wfn )
Unified/htmlor.py:160:            text+=', <a href="http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#table=Jobs&date1=%s&date2=%s&sortby=site&task=wmagent_%s">1d</a>'%( date1, date2, wfn )
Unified/htmlor.py:162:            text+=', <a href="http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#table=Jobs&date1=%s&date2=%s&sortby=site&task=wmagent_%s"> 5h</a>'%( date1, date2, wfn )
Unified/htmlor.py:164:            text+=', <a href="http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#table=Jobs&date1=%s&date2=%s&sortby=site&task=wmagent_%s"> 1h</a>'%( date1, date2, wfn )
Unified/htmlor.py:1030:            text+=', <a href="http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&refresh=0&table=Jobs&p=1&records=25&activemenu=1&site=%s&submissiontool=&check=submitted&sortby=activity&scale=linear&bars=20&date1=%s&date2=%s">1m</a>'%( site,date1m,now )
Unified/htmlor.py:1031:            text+=', <a href="http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&refresh=0&table=Jobs&p=1&records=25&activemenu=1&site=%s&submissiontool=&check=submitted&sortby=activity&scale=linear&bars=20&date1=%s&date2=%s">1w</a>'%( site,date7d,now )
Unified/htmlor.py:1032:            text+=', <a href="http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&refresh=0&table=Jobs&p=1&records=25&activemenu=1&site=%s&submissiontool=&check=submitted&sortby=activity&scale=linear&bars=20&date1=%s&date2=%s">1d</a>'%( site,date1d,now )
Unified/htmlor.py:1033:            text+=', <a href="http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&refresh=0&table=Jobs&p=1&records=25&activemenu=1&site=%s&submissiontool=&check=submitted&sortby=activity&scale=linear&bars=20&date1=%s&date2=%s">5h</a>'%( site,date5h,now )
Unified/htmlor.py:1034:            text+=', <a href="http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&refresh=0&table=Jobs&p=1&records=25&activemenu=1&site=%s&submissiontool=&check=submitted&sortby=activity&scale=linear&bars=20&date1=%s&date2=%s">1h</a>'%( site,date1h,now )
utils.py:2389:            info = json.loads( os.popen('curl -s "http://dashb-cms-job.cern.ch/dashboard/request.py/jobsummary-plot-or-table2?site=%s&check=submitted&sortby=activity&prettyprint"' % site ).read() )
```

### PR DESCRIPTION
**Pull request by sharad1126**
Fixes #487 #488 

#### Status
tested  

#### Description
<Description of the changes proposed.>

#### Is it backward compatible (if not, which system it affects?)
NO

#### Related PRs
#458 

#### External dependencies / deployment changes
dash-ssb*, dash-cms*

#### Mention people to look at PRs
@z4027163 @vlimant @amaltaro

### CODE REVIEW

**Comment by sharad1126** [comment]
Looks like we are using only one dashb-ssb - ssb_237(https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L2176). rest ssb metrics[159,160,136] are never called.

**Comment by sharad1126** [comment]
@vlimant I have made the queries and the command that can grab the info from the monit. just need more retuning as it provides a different json and not exactly the same as we used to get from dashb-ssb. 

regarding https://github.com/CMSCompOps/WmAgentScripts/pull/489/commits/c1aa5faa083c67f0c537b1d18bf24d2cb7942c20, the urls were decommissioned in 2018 itself. I need to check if there is some alternatives to those.

**Comment by sharad1126** [comment]
@scarletnorberg @drkovalskyi @vlimant @jenimal @z4027163 do you guys think anyone has been using these links in htmlor else someone would have surely complaint about the links not working since it was decommissioned. 
I don't think even people know where this exists so I will just post the place where it is:
```
Worflow on-going (3511) ongoing elog queues log postlog equ comp lasting [Click to show/hide]
```
 on https://cms-unified.web.cern.ch/cms-unified// page.
when you click on by workflow - there are links to report, 1m, 1w, 5d, etc. for every workflow and there we use these dash-cms* links.

**Comment by vlimant** [comment]
those links have been extremely useful at times, getting the templated url is of good practice, and will help

**Comment by sharad1126** [comment]
https://its.cern.ch/jira/browse/CMSMONIT-188
@vlimant @drkovalskyi @jenimal  can you please comment on this ticket as no one remembers what these URLs use to give. They did shift the web-job2 to Grafana but I see only CRAB info there as it was requested by Stefano.

**Comment by drkovalskyi** [comment]
Let's create an issue to review the old links and try to find proper replacements. For now it makes sense to comment out all this stuff since it no longer work. Please resolve the conflict and merge it.

**Pull request merged**
