### PR TITLE
faster DBS loop

### PR DESCRIPTION
**Pull request by vlimant**
is this what you had in mind @yuyiguo #346

### CODE REVIEW

**Comment by vlimant** [comment]
about 5 times faster on /SingleMuon/Run2018D-v1/RAW for example

@sharad1126 fyi

**Comment by yuyiguo** [comment]
You might use date/time to limit the blocks and it could be even faster if you were only interested to certain time or you could add new times each time.  I don't know the details your use case.

**Comment by vlimant** [comment]
we want all blocks

**Comment by yuyiguo** [comment]
Got it.

**Pull request merged**
