### PR TITLE
WIP: Remove unused files

### LINKED ISSUE #733: Remove unused/redundant files
**Impact of the bug**
Project management

**Describe the bug**
There are many unnecessary legacy files in the repository which are not used anymore. Less files we have, better we manage them.

**Expected behavior**
We should remove all the redundant files. If we need them for some reason in the future, we can unearth them from the history. Some candidates:
```
phedexClient.py
Unified/subscribor.py
Unified/stuckor.py
Unified/inputs_summary.py
Unified/phedexClient.py
PhEDEXFix/*
```
and many others...

We should scan the repo and get a full list. 

**Additional context and error message**
@z4027163  FYI

### PR DESCRIPTION
**Pull request by haozturk**
Fixes #733 

#### Status
in progress

#### Description
This PR removes the unused/redundant files in the repository to ease the management of the code. I am checking if a file is being used by any running modules/acron job. If not, I am checking if it is a standalone script. If I have no clue about the script and if the script looks outdated to me, I am removing it. In the first batch, I have removed the following files:
```
phedexClient.py 
Unified/phedexClient.py 
deleteInvalidOutput.py
Unified/corrupted_files.py
Unified/inputs_summary.py
closeOutWorkflows.py
getInputLocation.py
Unified/subscribor.py 
subscribecycle.sh 
Unified/stuckor.py 
PhEDEXFix/*
fixPhEDEx.py
fix_merge_acdc.py
condor_rm48h.sh
```

#### Is it backward compatible (if not, which system it affects?)
No

#### Related PRs
None

#### External dependencies / deployment changes
None

#### Mention people to look at PRs
@z4027163 Let's do not merge it, yet. I will continue removing files. Could you please cross-check the files that I removed? Let's have a reason for each file that we keep in the repository and preferably a short documentation on how to use it. If you are also going to remove files, please remove one file per one commit, so that we can revert it easily if necessary.

### CODE REVIEW

**Comment by haozturk** [comment]
For cleaning purposes, I have scanned the whole repository for unnecessary files, removed some of them and moved the most of them to the `archive` directory. I have paid attention if the file is being used by any active process. @z4027163 @drkovalskyi  @amaltaro please let me know if you are concerned with the removal of a file. You can find all the changes below. Note that this PR removes/archives ~100 files. I took also some notes about the files in the #733 if you want to have a look.
```
Move Unified/step_chain_test.py to archive
Move Unified/spreador.py to archive
Move Unified/rulor.py to archive
Move Unified/presence.py to archive
Move Unified/phinject.py to archive
Move Unified/efficiencor.py to archive
Move Unified/collector.py to archive
Move Unified/assignSchemaTest.py to archive
Move Unified/assignSessionTest.py to archive
Move Unified/GQ.py to archive
Move WMCoreService directory to archive
Move StoreResults directory to archive
Move CondorMonitoring directory to archive
Move ComissionT2Site directory to archive
Move WFComplete_submitter.sh to archive
Move WorkflowJobInfo.py to archive
Move WorkflowSummary.py to archive
Move analyzeDuplicates.py to archive
Move assignDatasetToSite.py to archive
Move closeOutWorkflowsFiltered.py to archive
Move closeOutWorkflowsWeb.py to archive
Move component_down.py to archive
Move condor_global_overview.py to archive
Move condor_overview.py to archive
Move condor_overview2.py to archive
Move copyLFNfromSite.sh to archive
Move createStoreResults.py to archive
Move createStoreResults_updated.py to archive
Move extendWorkflow.py to archive
Move findWorkflows.py to archive
Move gqcycle.sh to archive
Move injectHarvest.py to archive
Move inputscycle.sh to archive
Move killWorkflowAgent.py to archive
Move lastlog.sh to archive
Move listWorkflows.py to archive
Move logscycle.sh to archive
Move notCustodialDatasets.py to archive
Move pledged.py to archive
Move pokeeos.sh to archive
Move processingCampaignOverview.py to archive
Move resubmitUnprocessedBlocks.py to archive
Move resubmitWithBlockBlacklist.py to archive
Move rmOldJobs.sh to archive
Move setDDM.sh to archive
Move setenvscripts.sh to archive
Move site_view.py to archive
Move stuckRequestDiagnosis.py to archive
Move test-env.sh to archive
Created archive directory for old scripts
Remove WorkflowPercentage.py
Remove condor_rm48h.sh
Remove fix_merge_acdc.py
Remove fixPhEDEx.py
Remove PhEDEXFix directory
Remove stuckor.py
Remove subscribecycle.sh
Remove Unified/subscribor.py
Remove getInputLocation.py
Remove closeOutWorkflows.py
Remove Unified/inputs_summary.py
Remove Unified/corrupted_files.py
Remove deleteInvalidOutput.py
Remove phedexClient.py

```

**Comment by drkovalskyi** [comment]
I like the idea of cleaning things up, but it's a bit too aggressive.  For example the first entry Unified/step_chain_test.py is used to manually check if a given workflow can be converted to StepChain. Maybe it should be migrated to some area where we keep operator's tools and made more human friendly. I haven't looked at the rest of the list.
Anyway, at this point I think it's better to clean up more aggressively and recover what's missing when it's needed than getting stuck in some sort of a review for each thing that we have on the list.

**Comment by haozturk** [comment]
@drkovalskyi I agree with your point in the sense that it sounds more effective to be aggressive at this point and recover later when it's necessary.

Thanks for pointing out the use case of `Unified/step_chain_test.py`. I put it back. I am planning to create a folder called `tools` in the root directory and move every standalone script there with its proper manual/documentation here: https://github.com/CMSCompOps/WmAgentScripts/wiki/Standalone-scripts

**Comment by drkovalskyi** [comment]
Sounds like a good plan.

**Pull request merged**
