### PR TITLE
Use single dbsApi/dbsApiWriter instance through whole code

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by vlimant** [comment]
Is this Thread.threading safe ?

**Comment by vkuznet** [comment]
It is actually question to Yuyi, as far as I can tell DbsApi should be thread safe. It setups persistent connection that can be re-used. Since in majority case you're fetching data there is no harm to re-use single instance, but for writer it is more important question.

**Comment by vlimant** [comment]
@vkuznet can you please rebase ?

**Comment by vkuznet** [comment]
It will take me a whole day to merge, therefore I'll delete my fork and then re-submit the changes. Here I'll close this PR, new one will appear soon.

**Pull request closed without merging**
