### PR TITLE
Give detailed report of pylint test failures

### PR DESCRIPTION
**Pull request by ishanrai05**
#### Status
ready

#### Description
Pylint will show errors only now.

#### Is it backward compatible (if not, which system it affects?)
Yes

#### Mention people to look at PRs
@sharad1126 @amaltaro

### CODE REVIEW

**Comment by ishanrai05** [comment]
we also have the option to disable refactor and convention using `--disable=R,C`. Do we want to do that?

**Comment by amaltaro** [comment]
I'd rather keep seeing those in the reports, but doesn't fail the checks only based on them.

**Comment by sharad1126** [comment]
I'd agree with @amaltaro

**Comment by sharad1126** [comment]
@ishanrai05 any updates on this?

**Comment by sharad1126** [comment]
@ishanrai05 can you please update this PR making sure pylint fails only on errors and warnings?

**Comment by ishanrai05** [comment]
link to [test](https://github.com/ishanrai05/WmAgentScripts/pull/3)

**Comment by ishanrai05** [comment]
The pylint will not fail on errors now. It will simply give a report.

**Pull request merged**
