### PR TITLE
add review dog with shell check

### PR DESCRIPTION
**Pull request by ishanrai05**
#### Status
Ready. Tested on my branch [here](https://github.com/ishanrai05/WmAgentScripts/pull/2)

#### Description
I added a review bot that will comment on the line with the lint error and link to how to solve it. It only works on changed lines.

#### Is it backward compatible (if not, which system it affects?)
Yes

#### Mention people to look at PRs
@sharad1126 @amaltaro

### CODE REVIEW

**Comment by sharad1126** [comment]
@ishanrai05 why did you remove the action to work on `push`?

**Comment by ishanrai05** [comment]
`pull request` action will work even if we add a commit to our existing PR. I tested this on my branch on the link provided above. The `push` and `pull request` action are causing a double build.

**Comment by sharad1126** [comment]
@ishanrai05 yes but it won't work in case some one by mistake pushes directly to GH without a PR. so please change it to push and PR both. thanks.

**Comment by ishanrai05** [comment]
`reviewdog` does not work on `push` event because needs a `pull request` to leave comments on. So I created another `yaml` file which will run on `push` event.

**Pull request merged**
