### PR TITLE
swift re-entry of clones

### PR DESCRIPTION
**Pull request by vlimant**
towards #311

### CODE REVIEW

**Comment by vlimant** [comment]
@SvenjaPflitsch would you mind doing a couple of test with Sharhad and report for merging

**Comment by vlimant** [comment]
with @sharad1126

**Comment by SvenjaPflitsch** [comment]
@sharad1126 has killed and cloned the following workflow yesterday: 
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_B2G-PhaseIITDRFall17wmLHEGS-00057

Looking at the Unifed log of this task it worked, the old workflow has been set to trouble and the new one has been assigned already. 

@vlimant do you need more details or that we test this on more workflows?

**Comment by HEPTrkX** [comment]
sounds good

**Comment by vlimant** [comment]
sounds good

**Pull request merged**
