### PR TITLE
communication on locks

### PR DESCRIPTION
**Pull request by vlimant**
remove any usage of files for locking items and runtime lock

### CODE REVIEW

**Comment by vlimant** [comment]
dataset/blocks lock are in the cms_unified_admin.lock table, the lock of lock is in cms_unified_admin.lockoflock table

**Comment by maierbenedikt** [comment]
Hi JR, can you explain to me the logic of the rows+columns when doing 'SELECT * FROM CMS_UNIFIED_ADMIN."LOCKOFLOCK"' ?

(21, 0, 1542648520, 1542648583, 'vocms0275.cern.ch-1898141')
(1, 0, 1542648279, 1542648342, 'vocms0275.cern.ch-1897226')

**Comment by vlimant** [comment]
if there is any entry with .lock = true in the table, that means no go

**Comment by vlimant** [comment]
@maierbenedikt are you guys ready to switch over ?

**Comment by maierbenedikt** [comment]
Still testing, aiming for switching on Monday. What's the current cycle for which you expect the locked datasets in the database to change? Since yesterday evening I don't see new locks being added or old locks being removed. Could be a bug on my end though.

**Comment by vlimant** [comment]
the LockOfLock table was tested and ready for production when this PR gets merged.
there won't be any relevant entry until we do the merge ; which means 

1. you disable dynamo
2. I merge the PR, check for cycles
3. you check for visibility of lock + lock of lock, to renable dynamo

**Comment by maierbenedikt** [comment]
Ah ok, so you're saying that the content of the FROM CMS_UNIFIED_ADMIN."lock" table is not changing right now?

If so, and if you feel confident, we can either do it today or Monday.

**Comment by vlimant** [comment]
CMS_UNIFIED_ADMIN.lock is always up to date and the primary source of info.
CMS_UNIFIED_ADMIN.LOCKOFLOCK is not activated ATM, waiting for this PR to merge

**Comment by maierbenedikt** [comment]
Got it. Actually I just saw 6 entries being unlocked. Waiting for something new to be locked, and then we're good to go. I will let you know.

**Comment by maierbenedikt** [comment]
Ok we're ready.

**Comment by vlimant** [comment]
tell me when dynamo is off and I'll proceed

**Comment by maierbenedikt** [comment]
I switched off detox now. Please go ahead.

**Comment by vlimant** [comment]
I'll let you know when it looks safe to restart

**Comment by vlimant** [comment]
made a couple of adjustments. go ahead with your tests and restart when you're ready.
let's be on the lookout for deadlocks

**Pull request merged**
