### PR TITLE
Add debugging to _get_dashbssb

### PR DESCRIPTION
**Pull request by nsmith-**
Fixes #?

#### Status
In development

#### Description
Wrap json.loads() in a try-except block to print out what the return value was on json decode error

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
Following discussion in email thread

#### External dependencies / deployment changes
No dependency change

#### Mention people to look at PRs
@sharad1126

### CODE REVIEW

**Comment by sharad1126** [comment]
thanks @nsmith- . Also, thanks for formatting the code!

**Comment by vkuznet** [comment]
@nsmith- , @sharad1126 , there is no need to invoke curl as subprocess, instead I suggest to revisit code and replace curl with CMSMonitoring [monit.py](https://github.com/dmwm/CMSMonitoring/blob/master/src/python/CMSMonitoring/monit.py) module. It can query ES/InfluxDB and we'd like to keep single place to access MONIT rather have different implementation. Plus it is python implementation instead of external curl one.

**Comment by nsmith-** [comment]
For sure curl in a subprocess is not a good practice. But let's take this one step at a time and diagnose the problem at hand.

**Comment by vkuznet** [comment]
Then I suggest explicitly mark NOT TO Merge this PR in production. If you need to debug stuff, you may fix the running code, but then push proper implementation into production codebase.

**Comment by nsmith-** [comment]
I just made this as the most convenient way to share a code patch with Sharad. I have no opinion on whether this PR should get merged or not and leave it to unified people to decide.

**Comment by sharad1126** [comment]
Hi @nsmith- , @vkuznet , technically we did plan to do something similar but we cannot use JSONDecodeError as it is python3 and we are still in python2. 
I will be going through the suggestion of using CMSMonitoring monit.py module is it is all in python2 as well. 
Else, we will find some other alternative solution. Thanks.

**Comment by nsmith-** [comment]
Ah sorry, I've been in python3 land for too long!

**Comment by vkuznet** [comment]
Sharad, CMSMonitoring monit.py script is compatible with both versions of python.

**Pull request closed without merging**
