### PR TITLE
people should read status from DBs

### PR DESCRIPTION
**Pull request by vlimant**
removing a couple of files on eos, in favor or direct access in oracle of mongodb

### CODE REVIEW

**Comment by vlimant** [comment]
@dabercro is the console using statuses.json or oracle ?

**Comment by dabercro** [comment]
The old console is still using statuses.json. The new one isn't yet, but we will need a way to filter out old workflows.

**Comment by dabercro** [comment]
@vlimant Can you change this back? It was probably a bad idea to make major changes while I was on holiday. Now Sharad is telling me that the workflows are backing up again. If you really want to trim this stuff, we'll either need the new console first or a larger effort on the old one.

**Comment by vlimant** [comment]
@dabercro I thought the console was reading from the db directly.
the file can be added back ; can you point to where the file is accessed and we try to hack in the access from the read-only account

**Comment by vlimant** [comment]
the new console should use the direct access BTW and not even try to resort to that json file

**Comment by drkovalskyi** [comment]
I provided an example how to get this information easily from the database. So Dan should be able to just patch the code.

**Comment by dabercro** [comment]
Yeah, I pointed to that in https://github.com/CMSCompOps/WorkflowWebTools/issues/116 At a first glance, it didn't catch right out of the box, but I didn't have time to figure out why. Hopefully I have time today.

**Comment by dabercro** [comment]
It looks like everything is reading fine from the database now. Tomorrow I can confirm with Sharad that everything's working at our morning meeting.

**Comment by vlimant** [comment]
please continue on https://github.com/CMSCompOps/WorkflowWebTools/issues/116

**Pull request merged**
