### PR TITLE
enabling commisioning2020, removing Phase2HLTTDRWinter20MiniAOD, Run3…

### PR DESCRIPTION
**Pull request by scarletnorberg**
…Winter20NanoAOD, Run3Winter20MiniAOD, Run3Winter20DRPremix, based on email from (Campaigns not needed) never got enabled and never will so do not need to archieve

Fixes #<GH_Issue_Number>

#### Status
<In development | not-tested | on hold | ready>

#### Description
<Description of the changes proposed.>

#### Is it backward compatible (if not, which system it affects?)
<YES | NO>

#### Related PRs
<If it's a follow up work; or porting a fix from a different branch, please mention them here.>

#### External dependencies / deployment changes
<Does it require deployment changes? Does it rely on third-party libraries?> 

#### Mention people to look at PRs
<Always mention people to check and review proposed changed.>

### CODE REVIEW

**Comment by z4027163** [comment]
@sharad1126 It looks good to me. Can you double check it in case I miss something.  @haozturk fyi

**Comment by sharad1126** [comment]
@scarletnorberg @z4027163  I see there are 3 more campaigns again removed by Scarlet in the PR. May I know why so?

**Comment by sharad1126** [comment]
@scarletnorberg can you please reply so we can merge it. Also, if you are removing a campaign from campaigns.json, please don't forget to put it into archive_campaigns.json

**Comment by scarletnorberg** [comment]
Yes it even mentions in the Winter20NanoAOD, Run3Winter20MiniAOD, Run3Winter20DRPremix, based on email from (Campaigns not needed) never got enabled and never will so do not need to archived. If you look at the email " Campaigns not needed"

**Comment by sharad1126** [comment]
ok, I wasn't aware of the campaigns not needed thing. Thanks for explaining. will merge the PR now.

**Comment by sharad1126** [comment]
btw you meant 4 campaigns right?
Phase2HLTTDRWinter20MiniAOD, Run3Winter20DRPremix, Run3Winter20MiniAOD, Run3Winter20NanoAOD

**Comment by scarletnorberg** [comment]
Yes. There are 4 campaigns that were agreed with PDMV (Jordan) that will never be opened at all. This is one of the reasons I was asking about closing the JIRA. That email has these 4 listed: Phase2HLTTDRWinter20MiniAOD, Run3Winter20DRPremix, Run3Winter20MiniAOD, Run3Winter20NanoAOD they had been sitting for months without opening and I even saw other campaigns that filled a void if there was a void.

**Pull request merged**
