### PR TITLE
check file stat after copying

### PR DESCRIPTION
**Pull request by thongonary**
#### Status
<In development | not-tested >

#### Description
https://cern.service-now.com/service-portal/view-incident.do?n=INC2095005
After copying the file, should check if the destination file in EOS has file size > 0, else retry

#### Is it backward compatible (if not, which system it affects?)
YES 

#### Mention people to look at PRs
@sharad1126

### CODE REVIEW

**Comment by sharad1126** [comment]
also should we use eoscp instead of cp as suggested by Maria in the ticket?

**Comment by thongonary** [comment]
> are we changing the value of bail_and_email to true?
No we change it to False.

> This will still only check the size but we don't know the content. many times eos just copies '@' in the file and the file size isn't 0.
If that's true, can you report in the ticket to Maria? She claimed that when the copy fails the destination file is blank and suggested me to do stat check.

**Comment by sharad1126** [comment]
> > are we changing the value of bail_and_email to true?
> 
> No we change it to False.
> 
> > This will still only check the size but we don't know the content. many times eos just copies '@' in the file and the file size isn't 0.
> 
> If that's true, can you report in the ticket to Maria? She claimed that when the copy fails the destination file is blank and suggested me to do stat check.

but then how are you going to get in the if block on line 1375?

**Comment by sharad1126** [comment]
Also, as mentioned by Maria, we need to use one of these options, right?

```
1. Still using cp, with that option we are a bit blind with the possible error but still we can work with it:
a) Set the env variable EOS_FUSE_DEBUG=1 and EOS_FUSE_LOGLEVEL=7 in the file /etc/sysconfig/eosd_env

2. Use eoscp or xrootcp:
a) Set the env variable XRD_LOGLEVEL=Dump
b) would be better use the subprocess module in order to get also the error, if there is any.

Then for both options, I would like that you collect the time that is taking to run the writing command, so you calculate the start_time and the end_time, before and after it.
```

**Comment by thongonary** [comment]
> but then how are you going to get in the if block on line 1375 or 1383 when the copy fails?

It was my way of commenting it out. After 5 failed copy attempt they will send an email anyway.

> Also, as mentioned by Maria, we need to use one of these options, right?

Yes. I haven't had time to implement it.

**Comment by thongonary** [comment]
@sharad1126 please add the following:
1. Check file stat of both source and destination file
2. Use `subprocess` instead of `os`, as instructed by Maria to save the log.

**Pull request merged**
