### PR TITLE
script to remove campign and put in archive

### PR DESCRIPTION
**Pull request by sharad1126**
Feature to remove campaign from mongodb, and campaigns.json and copy to archive_campaigns.json

#### Status
tested and ready 

#### Description
The script helps to remove the unwanted campaign from the mongodb,campaigns.json and copy it to archive_campaigns.json.

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
https://github.com/CMSCompOps/WmAgentScripts/pull/430

#### External dependencies / deployment changes
needs campaigns.json, archive_campaigns.json and campaignsConfiguration.py 

#### Mention people to look at PRs
@thongonary @optimisticcynic can you please have a look?

### CODE REVIEW

**Comment by thongonary** [comment]
The code looks OK, just kinda suboptimal in terms of style.

**Comment by sharad1126** [comment]
do you suggest any changes? from my side, I prefer to keep the code as efficient and small as possible so other people can understand it whenever needed.

**Comment by thongonary** [comment]
I think you can open it once for both read and write ("w+")

**Comment by sharad1126** [comment]
tried doing that but it gives issues with r+ or w+ in indentation and deletion. Guess this is the better way to read and write it separately when needed.

**Comment by amaltaro** [comment]
My 2cents here is.
```
if not options.name:
  print "enter a campaign name with -n <campaign name>"
  sys.exit(1)

with open('campaigns.json','r') as campaigns:
  campaign_db = json.load(campaigns)
with open('archive_campaigns.json','r') as outfile:
  destination = json.load(outfile)

for key,value in campaign_db.items():
...
```

So, files being read, you open, load into memory and move on , no need to keep all that nested structure.
If you want to avoid problems in the future, do NOT use tabs in a python source code.

**Comment by sharad1126** [comment]
I wouldn't like to open the archive_campaigns.json file unless I know that the campaign actually exists

**Comment by amaltaro** [comment]
That's a valid point. However:
a) json.load return a dict, so there is no need to iterate over it, simply do a `if key in campaign_db` and move on
b) unneeded nested code
c) opening files inside the for loop gives the impression you would need to open it many times, but you dont
d) code can be made much cleaner and simpler

Last but not least, it's a good practice to run a code reformat on brand new source code such that you keep it tidy and following PEP coding style. Whatever editor/IDE works for you.

**Pull request merged**
