### PR TITLE
Creating JIRA for agent error

### PR DESCRIPTION
**Pull request by vlimant**
this is the alpha version. there needs to be some veto on setting a JIRA.
Heartbeat ? find a time over which to make the JIRA maybe ?
Components in auto-restart ? certainly not. Which are they ?

@scarletnorberg

### CODE REVIEW

**Comment by vlimant** [comment]
works : https://its.cern.ch/jira/browse/CMSCOMPPR-4607

**Comment by vlimant** [comment]
it can be merged if @scarletnorberg is happy with this

**Comment by amaltaro** [comment]
Isn't it better if it sets the alarm timestamp in the jira title? "week 4" doesn't look clear at all.

**Comment by vlimant** [comment]
is the timestamp "unique" in this case. "week 4" allows to have only one jira per component per week per error type per agent.

**Comment by amaltaro** [comment]
I see, "week 4" would make it easier to recycle tickets. Yes, timestamp in wmstats is unique.

**Comment by vlimant** [comment]
I wasn't clear : the timestamp identifies the crash, or when the error is reported to wmstats by the agent ?

**Pull request merged**
