### PR TITLE
Create JIRA for long running workflows

### PR DESCRIPTION
**Pull request by vlimant**
for #384 . With  
```

jira_priority_and_delays = { 11000 : 14,
                                 90000 : 21}
```
it is going to make a jira for wf with prior>=110k after 14 days, >= 90 after 21days, and nothing else.
With
`         ping_on_jira = 7 *(24*60*60) # 7 days `
it will insert a new comment every 7 days after the last comment in the jira

### CODE REVIEW

**Comment by vlimant** [comment]
https://its.cern.ch/jira/browse/CMSCOMPPR-4808 for a test

**Comment by vlimant** [comment]
the calculation of the delay in this case should be taken from the last time the priority was set the current value

**Comment by vlimant** [comment]
@drkovalskyi do you want this in ?

**Comment by drkovalskyi** [comment]
As we discussed offline the answer was yes :)

**Pull request merged**
