### PR TITLE
Migrate dashb_ssb metrics to grafana

### LINKED ISSUE #488: remove the commented dashb-ssb links and migrate 4 used dashb-ssb to monit call
**Impact of the bug**
Once the dashb-ssb stops on 17/2/2020, the json files will not be working. 

**Describe the bug**
Migration of the following dashb-ssb links to monit call. 
```
utils.py:1850:            'getter' : lambda : json.loads(os.popen('curl -s --retry 5 "http://dashb-ssb.cern.ch/dashboard/request.py/getplotdata?columnid=136&batch=1&lastdata=1"').read())['csvdata'],
utils.py:1858:            'getter' : lambda : json.loads(os.popen('curl -s --retry 5 "http://dashb-ssb.cern.ch/dashboard/request.py/getplotdata?columnid=237&batch=1&lastdata=1"').read())['csvdata'],
utils.py:1866:            'getter' : lambda : json.loads(os.popen('curl -s --retry 5 "http://dashb-ssb.cern.ch/dashboard/request.py/getplotdata?columnid=159&batch=1&lastdata=1"').read())['csvdata'],
utils.py:1874:            'getter' : lambda : json.loads(os.popen('curl -s --retry 5 "http://dashb-ssb.cern.ch/dashboard/request.py/getplotdata?columnid=160&batch=1&lastdata=1"').read())['csvdata'],
```

**How to reproduce it**
dashb-ssb links will not work after decommissioning.

**Expected behavior**

**Additional context and error message**
Using the token from monit, make a call and replace the python curl call.

### PR DESCRIPTION
**Pull request by sharad1126**
Fixes #488 

#### Status
tested 

#### Description
The pull request migrates all json calls from dashb-ssb to grafana calls.

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
#489 

#### External dependencies / deployment changes
dashb-ssb* metrics, monit-grafana

#### Mention people to look at PRs
@vlimant @amaltaro @z4027163

### CODE REVIEW

**Comment by sharad1126** [comment]
there is a problem with that apparently. Monit creates new documents for all sites as soon as any one is updated and so we need the latest one every time. So, basically whenever we use these, we have to run init in order to get the latest timestamp always. Also, the json key names have changed resulting in other changes.

**Comment by sharad1126** [comment]
Sure, I can just put 'data.' before querying the json in that line. I'll make the changes and commit

**Comment by sharad1126** [comment]
```
>>> from utils import siteInfo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1557  100  1046  100   511   8301   4055 --:--:-- --:--:-- --:--:--  8368
>>> si = siteInfo()
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1413  100   903  100   510   9814   5543 --:--:-- --:--:-- --:--:--  9923
cache hit site_storage
cache hit mcore_ready
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1558  100  1047  100   511   8700   4246 --:--:-- --:--:-- --:--:--  8725
cache miss ssb_core_production
The dotted field 'metadata.timestamp' in 'data.0.fields.metadata.timestamp' is not valid for storage.
cache miss ssb_core_max_used
The dotted field 'metadata.timestamp' in 'data.0.fields.metadata.timestamp' is not valid for storage.
cache miss ssb_core_cpu_intensive
The dotted field 'metadata.timestamp' in 'data.0.fields.metadata.timestamp' is not valid for storage.
cache hit mss_usage
cache hit site_queues
cache hit detox_sites
cache hit gwmsmon_totals
cache hit gwmsmon_site_summary
too large to go in mongo. in file instead
cache hit gwmsmon_prod_maxused
cache hit gwmsmon_prod_site_summary
>>> 
```

**Comment by sharad1126** [comment]
@vlimant can you please check ```The dotted field 'metadata.timestamp' in 'data.0.fields.metadata.timestamp' is not valid for storage.
``` is coming from and how to solve this? 
looks like a mongodb warning.

**Comment by sharad1126** [comment]
from https://stackoverflow.com/questions/30014243/mongoerror-the-dotted-field-is-not-valid-for-storage/40584451, seems like we can solve this by updating the mongo version >=3.6

**Comment by sharad1126** [comment]
This would end up in making a new json as the new json returned by MONIT isn’t straight forward as it was earlier in direct api calls.

**Comment by vlimant** [comment]
it would be extremely useful if @vkuznet could provide you with a pycurl implementation of all this, instead of relying the lousy legacy os.popen(curl). Even better, is there a recommended graphana python API?

**Comment by sharad1126** [comment]
changed it to the most cleanest way I could think of. Please have a look and check, so we can merge it.

**Comment by vlimant** [comment]
> ['_source']['data'] should probably be factored in the getter

**Comment by sharad1126** [comment]
> > ['_source']['data'] should probably be factored in the getter

but that would end up in making a new json by parsing the whole json that we get from grafana. why should we make new json if we can use the one we get from grafana?

**Comment by vkuznet** [comment]
Few things, since I don't know full context of stuff you're trying to accomplish:
- If you want to access programmatically MONIT data-source you should use [CMSMonitoring monit.py](https://github.com/dmwm/CMSMonitoring/blob/master/src/python/CMSMonitoring/monit.py) tool we developed. It can query ES and InfluxDB data-source
- if you want to inject data to MONIT you better use flat dict structure
- data injection to MONIT should be done via [CMSMonitoring StompAMQ.py](https://github.com/dmwm/CMSMonitoring/blob/master/src/python/CMSMonitoring/StompAMQ.py) module
- if you want to use python pycurl module, you better use [WMCore pycurl_manager.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/pycurl_manager.py)

If you need my help on any subject please provide clear definition of the problem.

**Pull request merged**
