### PR TITLE
allow to assign to all sites reading from a SE

### PR DESCRIPTION
**Pull request by vlimant**
@areinsvo @SvenjaPflitsch @prozober

### CODE REVIEW

**Comment by vlimant** [comment]
can you please try a couple of actions with the branch and we get this in?

**Comment by vlimant** [comment]
@SvenjaPflitsch can you please try with @prozober a couple of acdc to test this

**Comment by vlimant** [comment]
@sharad1126 this is likely to solve the T2_CH_CSCS => T0_CH_CSCS_HPC issue

**Comment by sharad1126** [comment]
ok, so should we merge this in this case? @thongonary FYI

**Comment by vlimant** [comment]
you'd have to test this with actor on some specific wf/actions

**Comment by vlimant** [comment]
remember this @sharad1126  ?

**Comment by vlimant** [comment]
FYI @dabercro

**Comment by sharad1126** [comment]
Thanks for reminding. will test the PR with actor for that very specific workflow.

**Comment by sharad1126** [comment]
@vlimant @z4027163 we are still not able to get the site properly assigned with PR. 
```
{
  "pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677": {
    "Action": "acdc", 
    "Reasons": [], 
    "ACDCs": [], 
    "user": "sagarwal", 
    "Parameters": {
      "TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeLHEoutput": {
        "cores": "", 
        "sites": [
          "T2_CH_CSCS"
        ], 
        "memory": ""
      }, 
      "TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeRAWSIMoutput": {
        "cores": "", 
        "sites": [
          "T2_CH_CSCS"
        ], 
        "memory": ""
      }
    }
  }
}
[
  "pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677"
]
----------------------------------------------------------------------------------------------------
Looking at pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677 for recovery options
Tasks is 
{
  "TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeLHEoutput": {
    "cores": "", 
    "sites": [
      "T2_CH_CSCS"
    ], 
    "memory": ""
  }, 
  "TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeRAWSIMoutput": {
    "cores": "", 
    "sites": [
      "T2_CH_CSCS"
    ], 
    "memory": ""
  }
}
using pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677
Where to run = 
{u'/pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0': [u'T1_IT_CNAF', u'T2_DE_DESY', u'T2_TR_METU', u'T2_AT_Vienna', u'T2_CH_CSCS', u'T2_UA_KIPT', u'T2_PK_NCP', u'T2_US_Purdue', u'T2_TW_NCHC', u'T2_FI_HIP', u'T2_UK_SGrid_RALPP', u'T2_FR_GRIF_LLR', u'T2_BE_UCL', u'T2_ES_IFCA', u'T2_DE_RWTH', u'T2_UK_SGrid_Bristol', u'T2_FR_IPHC', u'T1_ES_PIC', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_IT_Legnaro', u'T2_US_Caltech', u'T2_UK_London_Brunel', u'T2_RU_JINR', u'T2_US_Vanderbilt', u'T2_GR_Ioannina', u'T2_IN_TIFR', u'T2_FR_CCIN2P3', u'T2_CN_Beijing', u'T1_FR_CCIN2P3', u'T2_US_Florida', u'T2_FR_GRIF_IRFU', u'T2_IT_Bari', u'T2_US_Nebraska', u'T1_DE_KIT', u'T2_US_UCSD', u'T2_CH_CERN_HLT', u'T2_ES_CIEMAT', u'T2_RU_IHEP', u'T2_US_Wisconsin', u'T2_HU_Budapest', u'T2_US_MIT', u'T2_BE_IIHE', u'T2_RU_INR', u'T2_CH_CERN', u'T2_PT_NCG_Lisbon', u'T1_RU_JINR', u'T2_BR_SPRACE'], u'/pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeRAWSIMoutput': [u'T2_CH_CSCS'], u'/pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeLHEoutput': [u'T2_CH_CSCS']}
Task names is TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeLHEoutput
Full task name is /pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeLHEoutput
[u'/pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0', u'/pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeRAWSIMoutput', u'/pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeLHEoutput']
{u'cores': u'', u'sites': [u'T2_CH_CSCS'], u'memory': u''}
Going to run at [u'T0_CH_CSCS_HPC', u'T2_CH_CSCS']
Initiating recovery
Inside single recovery!
ACDC payload
{u'cores': u'', u'sites': [u'T2_CH_CSCS'], u'memory': u''}
{"result": [
 {"cmsunified_ACDC0_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_200124_164018_3041": "OK"}
]}

ACDC created for task /pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeLHEoutput. Actions taken 
{"cores": "", "sites": ["T2_CH_CSCS"], "memory": ""}
really doing the assignment of the ACDC cmsunified_ACDC0_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_200124_164018_3041
These are the parameters to be used
{
  "SoftTimeout": 159600, 
  "BlockCloseMaxEvents": 200000000, 
  "MinMergeSize": 2147483648, 
  "BlockCloseMaxWaitTime": 172800, 
  "MaxMergeSize": 4294967296, 
  "NonCustodialGroup": "DataOps", 
  "NonCustodialSites": [], 
  "ProcessingVersion": 1, 
  "RequestName": "cmsunified_ACDC0_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_200124_164018_3041", 
  "SiteWhitelist": [
    "T0_CH_CSCS_HPC", 
    "T2_CH_CSCS"
  ], 
  "Team": "production", 
  "TrustSitelists": false, 
  "AutoApproveSubscriptionSites": [], 
  "UnmergedLFNBase": "/store/unmerged", 
  "CustodialSubType": "Replica", 
  "TrustPUSitelists": false, 
  "GracePeriod": 300, 
  "MergedLFNBase": "/store/mc", 
  "MaxMergeEvents": 20000000, 
  "CustodialSites": [], 
  "SiteBlacklist": [], 
  "RequestStatus": "assigned", 
  "NonCustodialSubType": "Replica", 
  "Dashboard": "production"
}
Assigned workflow: cmsunified_ACDC0_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_200124_164018_3041 to site: [u'T0_CH_CSCS_HPC', u'T2_CH_CSCS'] and team production
cmsunified_ACDC0_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_200124_164018_3041 was assigned for recovery
connectionpool._make_request(437) => https://its.cern.ch:443 "GET /jira/rest/api/2/search?jql=project%3DCMSCOMPPR+AND+summary~%22task_TOP-RunIISummer19UL16wmLHEGEN-00017%22&validateQuery=True&startAt=0&maxResults=-1 HTTP/1.1" 200 None (2020-01-24 16:40:27)
connectionpool._make_request(437) => https://its.cern.ch:443 "POST /jira/rest/api/2/issue/CMSCOMPPR-11352/comment HTTP/1.1" 201 1460 (2020-01-24 16:40:27)
CMSCOMPPR-11352 to progress
connectionpool._make_request(437) => https://its.cern.ch:443 "POST /jira/rest/api/2/issue/CMSCOMPPR-11352/transitions HTTP/1.1" 204 0 (2020-01-24 16:40:27)
Task names is TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeRAWSIMoutput
Full task name is /pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeRAWSIMoutput
[u'/pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0', u'/pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeRAWSIMoutput', u'/pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeLHEoutput']
{u'cores': u'', u'sites': [u'T2_CH_CSCS'], u'memory': u''}
Going to run at [u'T0_CH_CSCS_HPC', u'T2_CH_CSCS']
Initiating recovery
Inside single recovery!
ACDC payload
{u'cores': u'', u'sites': [u'T2_CH_CSCS'], u'memory': u''}
{"result": [
 {"cmsunified_ACDC0_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_200124_164027_8815": "OK"}
]}

ACDC created for task /pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677/TOP-RunIISummer19UL16wmLHEGEN-00017_0/TOP-RunIISummer19UL16wmLHEGEN-00017_0MergeRAWSIMoutput. Actions taken 
{"cores": "", "sites": ["T2_CH_CSCS"], "memory": ""}
really doing the assignment of the ACDC cmsunified_ACDC0_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_200124_164027_8815
These are the parameters to be used
{
  "SoftTimeout": 159600, 
  "BlockCloseMaxEvents": 200000000, 
  "MinMergeSize": 2147483648, 
  "BlockCloseMaxWaitTime": 172800, 
  "MaxMergeSize": 4294967296, 
  "NonCustodialGroup": "DataOps", 
  "NonCustodialSites": [], 
  "ProcessingVersion": 1, 
  "RequestName": "cmsunified_ACDC0_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_200124_164027_8815", 
  "SiteWhitelist": [
    "T0_CH_CSCS_HPC", 
    "T2_CH_CSCS"
  ], 
  "Team": "production", 
  "TrustSitelists": false, 
  "AutoApproveSubscriptionSites": [], 
  "UnmergedLFNBase": "/store/unmerged", 
  "CustodialSubType": "Replica", 
  "TrustPUSitelists": false, 
  "GracePeriod": 300, 
  "MergedLFNBase": "/store/mc", 
  "MaxMergeEvents": 20000000, 
  "CustodialSites": [], 
  "SiteBlacklist": [], 
  "RequestStatus": "assigned", 
  "NonCustodialSubType": "Replica", 
  "Dashboard": "production"
}
Assigned workflow: cmsunified_ACDC0_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_200124_164027_8815 to site: [u'T0_CH_CSCS_HPC', u'T2_CH_CSCS'] and team production
cmsunified_ACDC0_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_200124_164027_8815 was assigned for recovery
connectionpool._make_request(437) => https://its.cern.ch:443 "GET /jira/rest/api/2/search?jql=project%3DCMSCOMPPR+AND+summary~%22task_TOP-RunIISummer19UL16wmLHEGEN-00017%22&validateQuery=True&startAt=0&maxResults=-1 HTTP/1.1" 200 None (2020-01-24 16:40:33)
connectionpool._make_request(437) => https://its.cern.ch:443 "POST /jira/rest/api/2/issue/CMSCOMPPR-11352/comment HTTP/1.1" 201 1463 (2020-01-24 16:40:33)
CMSCOMPPR-11352 to progress
connectionpool._make_request(437) => https://its.cern.ch:443 "POST /jira/rest/api/2/issue/CMSCOMPPR-11352/transitions HTTP/1.1" 400 296 (2020-01-24 16:40:33)
transition to progress not successful
JiraError HTTP 400 url: https://its.cern.ch/jira/rest/api/2/issue/CMSCOMPPR-11352/transitions
	text: It seems that you have tried to perform a workflow operation (Start Progress) that is not valid for the current state of this issue (CMSCOMPPR-11352). The likely cause is that somebody has changed the issue recently, please look at the issue history for details.
	
	response headers = {'Content-Length': '296', 'X-Ausername': 'cmsunified', 'X-Arequestid': '1000x15868812x1', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "frame-ancestors 'self'", 'Content-Type': 'application/json;charset=UTF-8', 'X-Seraph-Loginreason': 'OK', 'X-Asessionid': 'xt3qfl', 'Server': 'nginx', 'Cache-Control': 'no-cache, no-store, no-transform', 'Date': 'Fri, 24 Jan 2020 15:40:33 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'X-Asen': 'SEN-2261235'}
	response text = {"errorMessages":["It seems that you have tried to perform a workflow operation (Start Progress) that is not valid for the current state of this issue (CMSCOMPPR-11352). The likely cause is that somebody has changed the issue recently, please look at the issue history for details."],"errors":{}}
{u'does_not_exist': [], u'already_reported': [], u'valid_key': True, u'valid_format': True, u'success': [u'pdmvserv_task_TOP-RunIISummer19UL16wmLHEGEN-00017__v1_T_191113_060524_6677']}
```

**Comment by vlimant** [comment]
what is the issue ? both T0_CH_CSCS_HPC and T2_CH_CSCS are declared to read from T2_CH_CSCS storage element ; hence they get in the whitelist

**Comment by sharad1126** [comment]
but as of now, we can't run production jobs at T0_CH_CSCS_HPC site so according to that shouldn't this site not pop up in site whitelist?

**Comment by vlimant** [comment]
then it has to be taken out completely

**Comment by z4027163** [comment]
@vlimant @sharad1126 The issue comes from website[1] which the SE_to_CE gets matched sites from.  The is a match pointing T2_CH_CSCS to T0_CH_CSCS_HPC which shouldn't be there. If someone can remove this match, the old version should be fine.

[1] https://cmsweb.cern.ch/sitedb/data/prod/data-processing

**Comment by vlimant** [comment]
the spurious presence of T0_..._HPC is not harming at all ; for proof  

https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_TOP-RunIISummer19UL16wmLHEGEN-00017

is done and announced, since the acdc ran at T2_CH_CSCS (which would not have been in whitelist without the PR). No further complication is required. Although @amaltaro can probably remove the site declaration if we are absolutely sure that this T0 will never come back

**Comment by amaltaro** [comment]
We actually no longer use SiteDB for anything in the WM system. It all relies on the CRIC service since a few months ago.

Still, the CSCS mapping seems to be the same in SiteDB and CRIC:
http://cms-cric.cern.ch/api/cms/site/query/?json&preset=data-processing

and that list of PSN x PNNs is managed by the Site Support team (together with the site admins). So we either:
a) filter that `T0_CH_CSCS_HPC` from the list of PSNs (CE), on our application
b) get in touch with the SST to see the status of that site and check whether anything can be done.

**Comment by vlimant** [comment]
it is worth updating this PR with using CRIC indeed

**Pull request merged**
