### PR TITLE
change the siteWhiteList for premix WF

### PR DESCRIPTION
**Pull request by z4027163**
As discussed in the P&R meeting, we no longer require goodIO (T2 sites) for premix WFs, instead we choose all the T2 sites.

@haozturk @sharad1126

### CODE REVIEW

**Comment by haozturk** [comment]
This looks good to me. I have a question regarding the [heavyRead function](https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L7333-L7340). So, it returns true, unless there is a `premix` string in the campaign or in the output datasets names. I checked several workflows and this logic was working. But I could not be sure if it works for all workflows. What do you think about this @z4027163 ?

**Comment by sharad1126** [comment]
@z4027163 I think we might want to check the heavyread function too again before we merge this. The second condition in heavyread() checks the output dataset to be `premix` and on checking a workflow which has `premix` as output, it basically uses `MinBias` as the secondary input to the wf. So, if this is the case, then the workflow should run only at goodIO sites right? And the PR in this case will be wrong.

**Comment by sharad1126** [comment]
@z4027163 I checked the heavyread() function and turns out, it returns `false` if the campaign name has premix or if the outputdataset of the wf has `premix`.  This basically means that if the heavyread() returns false, then the workflow running has MinBias as it's secondary dataset/PU. And therefore, this one should definitely go to goodIO. 
If the wf has a MinBias as a Secondary dataset and no premix output, then heavyread is true which means it goes to goodIO already. 
If the workflow has premix dataset as a secondary, then the heavyread() also returns false. Now this is the case when we are suppose to basically run this type of wf to all T0s, T1s and T2s with goodAAA

**Comment by z4027163** [comment]
@haozturk @sharad1126  Now change the heavyRead() function to check if there is minbias in secondary.

**Comment by sharad1126** [comment]
@z4027163 let me run this against some wfs which have secondary and will confirm you the output.

**Comment by sharad1126** [comment]
@drkovalskyi we have changed the heavyread function a bit here which I think makes our logic better now. Earlier it was creating a bit confusion. now we have made sure that only wfs with MinBias secondary gets the goodIO lists. If the secondary dataset is not MinBias, then we let it get assigned to all T2s as well.
@haozturk please paste 1-2 outputs in different comments in `` that you have checked with a single line as in which is secondary premix, secondary Minbias and other secondaries.

**Comment by sharad1126** [comment]
For a wf with premix secondary, the following sitewhitelist is now produced: 
```
wfi_premix = workflowInfo('cmsweb.cern.ch', 'pdmvserv_task_SUS-RunIIAutumn18FSPremix-00135__v1_T_200617_074223_3845')
lhe_pre, prim_pre, parent_pre, sec_pre, sites_allowed_pre = wfi_premix.getSiteWhiteList()
Initially allow [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_BR_SPRACE', u'T2_BR_UERJ', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_CN_Beijing', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_ES_IFCA', u'T2_FI_HIP', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_HU_Budapest', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_KR_KISTI', u'T2_PL_Swierk', u'T2_PT_NCG_Lisbon', u'T2_RU_IHEP', u'T2_RU_INR', u'T2_RU_ITEP', u'T2_RU_JINR', u'T2_TR_METU', u'T2_TW_NCHC', u'T2_UA_KIPT', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_UK_SGrid_Bristol', u'T2_UK_SGrid_RALPP', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_Wisconsin', 'T3_US_Colorado', 'T3_US_NERSC', 'T3_US_OSG', 'T3_US_PSC', 'T3_US_SDSC', 'T3_US_TACC']
Reducing the whitelist due to black list in campaign configuration
Removing [u'T2_CH_CERN_HLT']
[INFO] Sites allowing 5600 MB and 8 core are
[INFO] Sites ready for multicore: [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_BR_SPRACE', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_CN_Beijing', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_ES_IFCA', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_PL_Swierk', u'T2_PT_NCG_Lisbon', u'T2_RU_JINR', u'T2_TW_NCHC', u'T2_UA_KIPT', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_UK_SGrid_RALPP', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_Wisconsin', u'T3_CH_CERN_HelixNebula', u'T3_US_Baylor', u'T3_US_Colorado', u'T3_US_NERSC']
Removing sites due to 5600 MB and 8 core(s) requirements: [u'T2_BR_UERJ', u'T2_FI_HIP', u'T2_HU_Budapest', u'T2_KR_KISTI', u'T2_RU_IHEP', u'T2_RU_INR', u'T2_RU_ITEP', u'T2_TR_METU', u'T2_UK_SGrid_Bristol', 'T3_US_NERSC', 'T3_US_OSG', 'T3_US_PSC', 'T3_US_SDSC', 'T3_US_TACC']
[INFO] Sites allowing [u'slc6_amd64_gcc700', u'slc6_amd64_gcc700', u'slc6_amd64_gcc700']: [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_BR_SPRACE', u'T2_BR_UERJ', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_CN_Beijing', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_ES_IFCA', u'T2_FI_HIP', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_HU_Budapest', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_KR_KISTI', u'T2_PL_Swierk', u'T2_PT_NCG_Lisbon', u'T2_RU_IHEP', u'T2_RU_INR', u'T2_RU_ITEP', u'T2_RU_JINR', u'T2_TR_METU', u'T2_TW_NCHC', u'T2_UA_KIPT', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_UK_SGrid_Bristol', u'T2_UK_SGrid_RALPP', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_Wisconsin', u'T3_FR_IPNL', u'T3_UK_SGrid_Oxford', u'T3_US_Baylor', u'T3_US_Colorado', u'T3_US_Rutgers']
Reducing the whitelist to sites allowing [u'slc6_amd64_gcc700', u'slc6_amd64_gcc700', u'slc6_amd64_gcc700'] . Removing  []
After all of these, allowing: [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_BR_SPRACE', u'T2_CH_CERN', u'T2_CH_CSCS', u'T2_CN_Beijing', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_ES_IFCA', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_PL_Swierk', u'T2_PT_NCG_Lisbon', u'T2_RU_JINR', u'T2_TW_NCHC', u'T2_UA_KIPT', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_UK_SGrid_RALPP', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_Wisconsin', u'T3_US_Colorado']
```

**Comment by sharad1126** [comment]
For a wf with MinBias secondary, 
```
lhe,prim,_,sec,sites_allowed = wfi_minbias.getSiteWhiteList()
Initially allow [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_PL_Swierk', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_Wisconsin']
[INFO] Sites allowing 15900 MB and 8 core are
[INFO] Sites ready for multicore: [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_BR_SPRACE', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_CN_Beijing', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_ES_IFCA', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_PL_Swierk', u'T2_PT_NCG_Lisbon', u'T2_RU_JINR', u'T2_TW_NCHC', u'T2_UA_KIPT', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_UK_SGrid_RALPP', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_Wisconsin', u'T3_CH_CERN_HelixNebula', u'T3_US_Baylor', u'T3_US_Colorado', u'T3_US_NERSC']
Removing sites due to 15900 MB and 8 core(s) requirements: []
[INFO] Sites allowing [u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc630', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc630', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700']: [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_BR_SPRACE', u'T2_BR_UERJ', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_CN_Beijing', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_ES_IFCA', u'T2_FI_HIP', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_HU_Budapest', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_KR_KISTI', u'T2_PL_Swierk', u'T2_PT_NCG_Lisbon', u'T2_RU_IHEP', u'T2_RU_INR', u'T2_RU_ITEP', u'T2_RU_JINR', u'T2_TR_METU', u'T2_TW_NCHC', u'T2_UA_KIPT', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_UK_SGrid_Bristol', u'T2_UK_SGrid_RALPP', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_Wisconsin', u'T3_FR_IPNL', u'T3_UK_SGrid_Oxford', u'T3_US_Baylor', u'T3_US_Colorado', u'T3_US_Rutgers']
Reducing the whitelist to sites allowing [u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc630', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700', u'slc7_amd64_gcc630', u'slc7_amd64_gcc700', u'slc7_amd64_gcc700'] . Removing  []
After all of these, allowing: [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_PL_Swierk', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_US_Caltech',u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_Wisconsin']
```

**Comment by haozturk** [comment]
Test on another workflow which reads PREMIX dataset as secondary:
Workflow Name: `pdmvserv_task_EGM-RunIISummer19UL18DIGIPremix-00002__v1_T_200817_202014_7969`
The secondary dataset name: `/Neutrino_E-10_gun/RunIISummer19ULPrePremix-UL18_106X_upgrade2018_realistic_v11_L1v1-v2/PREMIX`
```
>>> wfi_premix2 = workflowInfo('cmsweb.cern.ch','pdmvserv_task_EGM-RunIISummer19UL18DIGIPremix-00002__v1_T_200817_202014_7969')
>>> lhe_pre2, prim_pre2, parent_pre2, sec_pre2, sites_allowed_pre2 = wfi_premix2.getSiteWhiteList()
Initially allow [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_BR_SPRACE', u'T2_BR_UERJ', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_CN_Beijing', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_ES_IFCA', u'T2_FI_HIP', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_HU_Budapest', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_KR_KISTI', u'T2_PL_Swierk', u'T2_PT_NCG_Lisbon', u'T2_RU_IHEP', u'T2_RU_INR', u'T2_RU_ITEP', u'T2_RU_JINR', u'T2_TR_METU', u'T2_TW_NCHC', u'T2_UA_KIPT', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_UK_SGrid_Bristol', u'T2_UK_SGrid_RALPP', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_Wisconsin', 'T3_US_Colorado', 'T3_US_NERSC', 'T3_US_OSG', 'T3_US_PSC', 'T3_US_SDSC', 'T3_US_TACC']
```
As you can see, it puts all available T2 sites to the site whilelist regardless of the goodIO list. For instance, `T2_HU_Budapest` is not in the goodIO list currently.

**Comment by haozturk** [comment]
Test on another workflow which reads MinBias dataset as secondary:
Workflow Name: `pdmvserv_task_HIN-HINPbPbAutumn18GSHIMix-00126__v1_T_200406_164149_7580`
The secondary dataset name: `/MinBias_Hydjet_Drum5F_2018_5p02TeV/HINPbPbAutumn18GS-103X_upgrade2018_realistic_HI_v11-v1/GEN-SIM`
```
>>> wfi_minbias2 = workflowInfo('cmsweb.cern.ch','pdmvserv_task_HIN-HINPbPbAutumn18GSHIMix-00126__v1_T_200406_164149_7580')
>>> lhe_min2, prim_min2, parent_min2, sec_min2, sites_allowed_min2 = wfi_minbias2.getSiteWhiteList()
Initially allow [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_IT_CNAF', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_PL_Swierk', u'T2_UK_London_Brunel', u'T2_UK_London_IC', u'T2_US_Caltech', u'T2_US_Florida', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_Wisconsin']
```
As you can see, it puts T2 sites which are present in the goodIO list to the site whilelist. i.e all allowed T2 sites are included in the goodIO list

**Comment by haozturk** [comment]
The new implemented logic works as expected according to the 4 workflows that we have tested. 

I agree that this version of the `heavyRead` function works better. Since it directly checks the secondary rather than the campaign name or the output dataset name.

**Comment by drkovalskyi** [comment]
> @drkovalskyi we have changed the heavyread function a bit here which I think makes our logic better now(as we discussed in pnr meeting). Earlier it was creating a bit confusion. now we have made sure that only wfs with `MinBias` secondary gets the `goodIO` lists. If the secondary dataset is not MinBias, then we let it get assigned to all T2s as well. @z4027163 I think we still need to make sure how to properly define this `goodIO` list though.
> @haozturk please paste 1-2 outputs in different comments in `` that you have checked with a single line as in which is secondary premix, secondary Minbias and other secondaries. @amaltaro fyi

To test goodIO I would select a heavy request using classical mixing and run it at each site to test if it can handle it. By heavy I mean something like PileUp 200 upgrade workflow. Set top priority and load the site completely one a time. Site that can handle it deserves to be on the goodIO list. I don't think we need to do such a test often and it can be done on demand by hand.

**Comment by haozturk** [comment]
We have created [a backfill test workflow](https://cmsweb.cern.ch/reqmgr2/fetch?rid=amaltaro_TEST-BACKFILL-task_TOP-RunIISummer19UL17wmLHEGEN-00126__v1_T_200918_131646_1557) which reads Premix secondary and assigned it to the sites which are candidates for `sites_with_goodAAA`. This workflow has 3 tasks and only task3 reads PU. Although the jobs created for task1 and task2 create a good amount of pressure on the sites (utilize the 50% of the sites on average), it is not the case for jobs created for task3 (# of jobs for task3 is less than 1% of the total number of jobs on average). Here is a brief log of the jobs created for each site for this workflow in terms of different tasks:
[backfill2_day3_wmstats_log.txt](https://github.com/CMSCompOps/WmAgentScripts/files/5254544/backfill2_day3_wmstats_log.txt)

**Comment by haozturk** [comment]
This is the 3rd test workflow (stepchain): https://cmsweb.cern.ch/reqmgr2/fetch?rid=amaltaro_TEST-BACKFILL-task_EGM-Run3Summer19wmLHEGS-00003__v1_T_200924_164243_9049
These are the tested sites: 
```
T2_BE_UCL,T2_BR_SPRACE,T2_CN_Beijing,T2_GR_Ioannina,T2_HU_Budapest,T2_IN_TIFR,T2_KR_KISTI,T2_RU_IHEP,T2_RU_INR,T2_RU_JINR,T2_TR_METU,T2_TW_NCHC,T2_UK_SGrid_Bristol,T2_UK_SGrid_RALPP,T2_US_Vanderbilt
```
The following list shows the number of failed and successful jobs:
```
    T2_GR_Ioannina: submitted-retry:1, pending:1,
    T2_HU_Budapest: success:773, submitted-running:4, retry:4,
    T2_IN_TIFR: success:919, submitted-running:2, retry:2,
    T2_CN_Beijing: success:10,
    T2_TR_METU: success:1,
    T2_RU_JINR: success:2182, submitted-running:4, retry:4,
    T2_KR_KISTI: success:574, submitted-running:13, retry:12, first:1,
    T2_UK_SGrid_Bristol: success:1,
    T2_TW_NCHC: failure-exception:1, cooloff-job:1, success:1064,
    T2_UK_SGrid_RALPP: submitted-running:23, retry:17, first:6, cooloff-job:1, success:1512,
    T2_BR_SPRACE: failure-exception:1, submitted-running:5, retry:4, first:1, success:1617,
    T2_US_Vanderbilt: transition:3, submitted-running:32, retry:34, pending:3, first:2, success:4585, cooloff-job:1, 
```
And the following plot shows the number of jobs created for this workflow and the total number of jobs running at each site to judge the pressure: https://monit-kibana.cern.ch/kibana/goto/9d786fd3ae0b93118c3d5f1867cd0564

From this information we can say that a good amount of pressure has been created for the following sites and jobs running on those site had a good success rate:
```
T2_TW_NCHC
T2_IN_TIFR
T2_HU_Budapest
T2_KR_KISTI
T2_BR_SPRACE
T2_RU_JINR
T2_UK_SGrid_RALPP
T2_US_Vanderbilt
```
So, I would say that these sites can be included in the goodAAA list.
The following sites did not get enough job, @amaltaro do you have an idea why?
```
T2_GR_Ioannina
T2_CN_Beijing
T2_TR_METU
T2_UK_SGrid_Bristol
```
And the following sites could not be tested since they were in drain during the assignment of the test workflow. They should be tested in the next rounds:
```
T2_AT_Vienna,T2_BR_UERJ,T2_ES_IFCA,T2_FI_HIP,T2_PK_NCP,T2_PL_Warsaw,T2_PT_NCG_Lisbon,T2_RU_ITEP,T2_UA_KIPT
```
@z4027163 FYI

**Comment by haozturk** [comment]
I have the run the assignor module to test the changes and the assignor works as expected:
```
pdmvserv_task_HCA-Run3Summer20GSHCAL-00002__v1_T_200930_164955_6074 to be assigned 
Reading premix
Initially allow [u'T1_DE_KIT', u'T1_ES_PIC', u'T1_FR_CCIN2P3', u'T1_RU_JINR', u'T1_UK_RAL', u'T1_US_FNAL', u'T2_BE_IIHE', u'T2_BR_SPRACE', u'T2_CH_CERN', u'T2_CH_CERN_HLT', u'T2_CH_CSCS', u'T2_DE_DESY', u'T2_DE_RWTH', u'T2_ES_CIEMAT', u'T2_FR_CCIN2P3', u'T2_FR_GRIF_IRFU', u'T2_FR_GRIF_LLR', u'T2_FR_IPHC', u'T2_HU_Budapest', u'T2_IN_TIFR', u'T2_IT_Bari', u'T2_IT_Legnaro', u'T2_IT_Pisa', u'T2_IT_Rome', u'T2_KR_KISTI', u'T2_PL_Swierk', u'T2_RU_JINR', u'T2_TW_NCHC', u'T2_UK_London_IC', u'T2_UK_SGrid_RALPP', u'T2_US_Caltech', u'T2_US_MIT', u'T2_US_Nebraska', u'T2_US_Purdue', u'T2_US_UCSD', u'T2_US_Wisconsin', 'T3_US_Colorado', 'T3_US_NERSC', 'T3_US_OSG', 'T3_US_PSC', 'T3_US_SDSC', 'T3_US_TACC']
```

**Comment by akurov** [comment]
Dear all,
We were never notified of storage or AAA bandwidth issues on our site.
Is there a chance for the T2_UA_KIPT site to be included in the list of goodIO and goodAAA sites?
Thanks,
Alexey

**Comment by haozturk** [comment]
Hi Alexey,

Thanks for your message. Currently, T2_UA_KIPT is not in either goodIO and goodAAA list. We recently tested AAA capabilities of all available sites and updated the list, but your site was in drain during the test. That's why we could not test it. There are several sites in this category which we are planning to test them soon.

**Pull request merged**
