### PR TITLE
HBF interface

### PR DESCRIPTION
**Pull request by vlimant**
goes in the direction of #360 . @sharad1126 you should get used to the command line tool.
there are some cleanup to be finalized so that we delete elements from the db when the workflow(s) go out of scope

### CODE REVIEW

**Comment by sharad1126** [comment]
ok you mean to bypass/force-complete/on-hold through the command line tool directly instead of adding it in the json files?

**Comment by vlimant** [comment]
with this PR, the afs files are totally deprecated and one adds something with

./wtcActions.py --action hold --keyword <workflow name, or keyword>

using --pop option to remove it from the DB.
at the moment, the db is fully synchronize with whether was in the json files on afs from the allowed users.

**Comment by sharad1126** [comment]
I think we can do this. It is better in all ways. Also I guess for #273 you mean we just pop it out right?

**Comment by sharad1126** [comment]
@vlimant what is the keyword here? I mean it should be name of the original workflow only right?

**Comment by vlimant** [comment]
either the workflow name of some text that is found in workflow names.
this could be evolved to regexp, if one feels it should ; I don't speak regexp :-(

**Comment by sharad1126** [comment]
ok great.. thanks ... I'll try this out once I have some request we need to bypass/force-complete/keep on hold. I will also add this to the twiki so it would be helpful

**Comment by sharad1126** [comment]
@thongonary FYI

**Comment by sharad1126** [comment]
So just to update for future reference - we need the proxy and export PYTHONPATH=$PYTHONPATH:/usr/lib64/python2.7/site-packages as it is a unified script.

**Comment by sharad1126** [comment]
@vlimant can you please confirm that since we are using the wtcActions.py and soon the JIRA search(once tested and merged), we don't need https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L6563 and https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L6497 and can be commented from the code?

**Comment by vlimant** [comment]
the file interface is completely unused already anyways, so those can go away

**Comment by todor-ivanov** [comment]
Thanks @vlimant @sharad1126

**Pull request merged**
