### PR TITLE
APIs to campaign configuration in ReqMgr2; updated Ops campaign script

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes https://github.com/dmwm/WMCore/issues/9310

#### Status
not-tested

#### Description
Summary of changes is:
* migrate from optparse to argparse (the former is not supported in python3)
* client APIs to interact with ReqMgr2 `campaignconfig` API.
* function to parse MongoDB campaign records and return WMCore formatted campaigns
* minor reorganization of the current campaignsConfiguration.py script
* then added a few extra methods such that we can reproduce MongoDB actions against CouchDB (ReqMgr2)
* updated `batchor` module to create (and delete) the same campaigns it updates in MongoDB.
* updated `closor` to delete campaigns in CouchDB as well

The usage of that script remains the same, same options and so on. The only difference is that it will try to make the same changes on two different backends, first MongoDB and then central CouchDB (production CMSWEB).

It uses the same logic - to convert unified campaign to wmcore campaign - as implemented in this script:
https://github.com/dmwm/WMCore/blob/master/bin/adhoc-scripts/parseUnifiedCampaigns.py

#### Is it backward compatible (if not, which system it affects?)
Sort of, shouldn't change anything in the unified ecosystem.

#### Related PRs
none

#### External dependencies / deployment changes
none

#### Mention people to look at PRs
none yet

### CODE REVIEW

**Comment by sharad1126** [comment]
yes @amaltaro , batchor is responsible for creating a new relval campiagn.

**Comment by sharad1126** [comment]
@amaltaro  FYI
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L298-L328
the last line 328, pops out the campaign name.

**Comment by amaltaro** [comment]
I had to fix one line in the campaignAPI module and those 5 main methods seem to be working Okay now.
I've pushed changes to the batchor module as well, which now will also create and delete campaigns in ReqMGr2.
I had a look at the closor, but it doesn't seem to be removing campaign configurations, so I see no changes needed there.

**Comment by sharad1126** [comment]
@amaltaro I tested the main campaigns.py again. please have a look. I checked couchdb too and looks like everything is working properly. I am just not sure about the batchor and closor as you don't yet have the campaigns in couchdb to remove them. 

```
[sagarwal@vocms0275 WmAgentScripts]$ python campaignsConfiguration.py --name RunIISpring25DR --configuration '{"go": false, "maxcopies": 1, "lumisize": -1, "resize" : "auto", "fractionpass" : 0.95}'
Campaign 'RunIISpring25DR' successfully created in central CouchDB
[sagarwal@vocms0275 WmAgentScripts]$ python campaignsConfiguration.py --name RunIISpring25DR
{
  "fractionpass": 0.95, 
  "go": false, 
  "lumisize": -1, 
  "maxcopies": 1, 
  "resize": "auto"
}
[sagarwal@vocms0275 WmAgentScripts]$ python campaignsConfiguration.py --name RunIISpring25DR --parameter maxcopies:5
updating RunIISpring25DR with values {'maxcopies': 5}
Campaign 'RunIISpring25DR' successfully updated in central CouchDB
[sagarwal@vocms0275 WmAgentScripts]$ python campaignsConfiguration.py --name RunIISpring25DR --remove
[sagarwal@vocms0275 WmAgentScripts]$ 
```

**Comment by amaltaro** [comment]
As suggested by @vlimant , I' changed this PR once again to use `reqmgr_url` from the `utils` module.
@sharad1126 I have squashed all the commits and it's good to go.

Once it gets merged, I'll fetch ALL the campaigns from MongoDB and inject them into central CouchDB (such that updates can be properly updated).

**Comment by sharad1126** [comment]
thanks @amaltaro . I will just merge it in this case. please go ahead and inject the campaigns from MongoDB.

**Comment by amaltaro** [comment]
Thanks you very much, Sharad! Most of the campaigns were already there when we tested loading a json into MongoDB (+CouchDB). So we should be all set. Please make sure Zac is aware of those changes and let me know if any issues arise.

**Pull request merged**
