### PR TITLE
Start overhaul of overflow routes.

### PR DESCRIPTION
**Pull request by bbockelm**
Includes code for a single route for all overflow jobs, but that isn't
enabled.  For now, just combine sufficiently similar routes.

Reduces the amount of work the JobRouter has to do by about 2-3x.  Once we get the 'master overflow rule' working, it'll be an additional 2-3x (about an order of magnitude combined).

### CODE REVIEW

**Comment by vlimant** [comment]
so you have tested this on several schedds ? which ones ?

**Comment by bbockelm** [comment]
This is on vocms0130 and vocms0310.

**Comment by bbockelm** [comment]
Deployed everywhere.

**Comment by vlimant** [comment]
@bbockelm this is crapping out for certain rules. We have to review and roll out if need be.

**Pull request merged**
