### PR TITLE
initial patch to use reqmgr2 api (Do not merge, yet)

### PR DESCRIPTION
**Pull request by ticoann**
There is error reported in assign script

### CODE REVIEW

**Comment by ticoann** [comment]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/changePriorityWorkflow.py#L11

Is this call still used?

**Comment by vlimant** [comment]
submitWorkflow(url, schema, reqmgr2=False) that should be set to True by default, assuming that we'll send any new workflow to reqmgr : that will make it less ambiguous in testing too

**Comment by vlimant** [comment]
+    elif request == "/reqmgr/reqMgr/closeout" or request == "/reqmgr/reqMgr/announce":
+        request = "/reqmgr/reqmgr2/data/request%s" % params['requestName']
+        newParams = {"RequestStatus": "closed-out", "cascade": params["cascade"]}

should be fixed, correct ?

**Comment by vlimant** [comment]
cParams["RequestStatus"] = params["RequestStatus"]
is wrong, correct ?

**Comment by vlimant** [comment]
is the announce cascade really a post instead of a put ?

**Comment by ticoann** [comment]
Thanks Jean-Roch, I fixed the bugs you found. 

> is the announce cascade really a post instead of a put ?

It seemed it was POST call in reqmgr1, but in reqmgr2 it is PUT call.

**Comment by vlimant** [comment]
+    params["Teams"] = teams 

it's supposed to be "Team" = teams[0]

**Comment by vlimant** [comment]
don't bother updating the patch, I am fixing this and will make the PR for testing once all is fixed.

**Comment by ticoann** [comment]
Thanks Jean-Roch, Could you post your patch, then? Since Jen need to test all her scripts as well.

**Comment by vlimant** [comment]
of course I will, working with a functioning patch will be more efficient

**Comment by ticoann** [comment]
Sure, but Jen was testing against this patch. So she has to test again with your patch. With the current fix you found and fixed Jen/Paola should be able to run there test since the test they ran was successful.
However, if it won't take much time to fix all for United script. I guess they can wait.

**Comment by vlimant** [comment]
unified is set. the branch I refered to functions, and can replace the patch which was buggy anyways.
what successful test ? those in https://github.com/dmwm/WMCore/issues/6640 have to restart anyways

**Pull request closed without merging**
