### PR TITLE
Added sendLog messages in checkSplitting

### PR DESCRIPTION
**Pull request by SvenjaPflitsch**

### CODE REVIEW

**Comment by SvenjaPflitsch** [comment]
I added a few sendLog messages under the regular printed messages so certain issues like the too large outputs show up on my radar when I check the critical messages.

**Comment by thongonary** [comment]
From https://its.cern.ch/jira/browse/CMSCOMPPR-3423 it seems the direct cause of this is just wrong TimePerEvent parameter. I'd suggest adding to the log "Change of splitting is on hold. Please double check TimePerEvent and SizePerEvent parameters of the request".

**Comment by vlimant** [comment]
@SvenjaPflitsch you want to clear this out?

**Comment by vlimant** [comment]
towards #304

**Pull request merged**
