### PR TITLE
check on jira

### PR DESCRIPTION
**Pull request by vlimant**
From the current outing of JIRA, modules are failing.
 should it be a soft or hard check is the question @sharad1126 @drkovalskyi

### CODE REVIEW

**Comment by sharad1126** [comment]
I think it should be a hard check. Else, if we have jira down again in future, it might again give errors and not create the tickets.

**Comment by drkovalskyi** [comment]
I think it should be a soft check. Unfortunately we cannot rely on JIRA as a critical service, since it's not supported as such. The tools should be able to fail graceful when JIRA is down and when it's back up it should be able to resume.

**Comment by vlimant** [comment]
hard check : it will fail gracefully when jira is down, but will do nothing useful until it's up
soft check : it will do what it is meant to do, and skip any jira manipulation.

soft or hard ?

**Comment by drkovalskyi** [comment]
I didn't mean to fail the component, i.e. the component should work even if JIRA is down. So for me it's soft check. @sharad1126 do you agree? If not, can you please clarify what's wrong with my view?

**Comment by sharad1126** [comment]
ok let's go with a soft check but what does 'skip any jira manipulation' exactly means?

**Comment by vlimant** [comment]
no jira comment, or opening ; which indeed might be impacting @sharad1126 smooth operation.

for closing and agent-JIRA, one needs to add it to the PR

**Comment by sharad1126** [comment]
yeah that's what I thought of and would have to do manual work in that case. So I'll switch back and prefer hard check

**Comment by drkovalskyi** [comment]
Why JIRA comments cannot be generated when JIRA is up in the next cycle? There won't be smooth operation if the component won't run and if JIRA is down for a long time we will mess production.

**Comment by vlimant** [comment]
the comments and action taken depend on the status the wf is in, at the next cycle the wf will have left the status it is in. I'd suggest a hard check (also because its the first time ever it was down) and switch to soft on the day it's down for a week and blocking ops

**Comment by drkovalskyi** [comment]
I like your suggestion, but I also have an alternative one. What if we skip workflows that need action, but JIRA is down? This way it will prevent JIRA taking down critical components. Is it hard to implement?

**Comment by vlimant** [comment]
too much refactoring needed act only on the things that'll need a jira action

**Comment by drkovalskyi** [comment]
Ok. In this case I agree with the hard check option.

**Comment by vlimant** [comment]
@sharad1126 can you please merge and keep an eye on all these modules with @scarletnorberg (UO)

**Comment by sharad1126** [comment]
sure

**Pull request merged**
