### PR TITLE
Opening campaigns that were successful with pilots and changing fract…

### PR DESCRIPTION
**Pull request by scarletnorberg**
MiniAODUL18Data PRCAMPAIGNS-169 pilot successful
MiniAODUL17Data PRCAMPAIGNS-168 pilot successful
RunIISummer19UL18MiniAODv2 PRCAMPAIGNS-174 pilot successful

Also updating all MC nanoAOD campaigns to have a fraction pass. Also updating the reminiAOD ones because assume that also needs to be higher then 95%. Data ones are left the same though.

### CODE REVIEW

**Comment by haozturk** [comment]
@scarletnorberg Can we have a fractionpass of `.99` instead of `.985` as we agreed on the former value with PdmV/PPD. Probably, the latter is also okay, but, I would prefer to have the exact value in order to avoid confusions in the future.

**Comment by scarletnorberg** [comment]
I could not remember what dima said and if 0.99 was still going to be more work. I wanted to set it to 0.98 I thought I would split the difference. I guess we can set it to 0.99 and if it is more work change it to something slightly lower which should be less work.

**Comment by scarletnorberg** [comment]
Updated

**Comment by scarletnorberg** [comment]
@haozturk updated

**Pull request merged**
