### PR TITLE
Consolidating Invalidation

### PR DESCRIPTION
**Pull request by vlimant**
@SvenjaPflitsch @areinsvo  can you please take a look and see whether the logic looks all OK?

### CODE REVIEW

**Comment by vlimant** [comment]
@areinsvo can you please find a way to verify this ?

**Comment by areinsvo** [comment]
@vlimant what did you have in mind? If @prozober let's us know when there is a clone request for actor, we could test that everything is invalidated the way it should be.

**Comment by prozober** [comment]
@areinsvo I cloned this request ~2 hours ago.

**Comment by vlimant** [comment]
@areinsvo can you please make the change and run some test on getFamilly with various arguments

**Comment by vlimant** [comment]
@SvenjaPflitsch can you please take over testing getFamilly with various argument ?

**Comment by SvenjaPflitsch** [comment]
I am on it, but it takes me somewhat longer because I need to understand some of the basics of how to test stuff in unified without disturbing anything else.

**Comment by vlimant** [comment]
you can change code and run on vocms275 which is the test node, not running anything for production. adding a couple of testing lines in Unified/sqtest.py is ok

**Comment by SvenjaPflitsch** [comment]
I ran the tests with this workflow: task_HIG-RunIIFall17wmLHEGS-01114 , which has been cloned in the past and has acdcs . 
I tried out both logics and I think what Allie proposed is right. These options give different results depending on the used logic: 

fam3 = wfi.getFamilly(details=False, only_resub=True, and_self=False)
-> Only the Resubmitted workflows
-> Works for Allies version, workflow itself is also listed in JRs version

fam4 = wfi.getFamilly(details=False, only_resub=True, and_self=True)
-> Allie: List everything
-> Jean-Roch: Lists only the original wf. 
-> This combination should not happen anyways, but I wanted to add it for completeness.

**Comment by vlimant** [comment]
@SvenjaPflitsch is the logic good to go ? I can resolved conflcts and merge

**Comment by SvenjaPflitsch** [comment]
I just checked the files again because I accidentally pushed a commit and then reverted it. The code now has Allies logic implemented, which is working.

**Comment by SvenjaPflitsch** [comment]
Something is wrong with this there are lots of "module actor failed" messages: 

Looking at pdmvserv_task_SUS-RunIIFall17wmLHEGS-00118__v1_T_180704_002941_8580 for recovery options
Let's try kill and clone: 
Going to clone pdmvserv_task_SUS-RunIIFall17wmLHEGS-00118__v1_T_180704_002941_8580
invalidating the workflow by traffic controller 
Traceback (most recent call last):
  File "Unified/actor.py", line 660, in <module>
    actor(url,options=options)
  File "Unified/actor.py", line 408, in actor
    inv_results = invalidate(url, wfi, and_self=True, only_resub=False, with_output=True)
TypeError: invalidate() got an unexpected keyword argument 'and_self'
abnormal termination

**Comment by vlimant** [comment]
https://github.com/CMSCompOps/WmAgentScripts/commit/27260bc14da0287c690897b7e164824dbece0b53

**Pull request merged**
