### PR TITLE
merge relval changes

### PR DESCRIPTION
**Pull request by AndrewLevin**
merging about 1 years worth of changes made for relval with the main WmAgentScripts repository

### CODE REVIEW

**Comment by amaltaro** [comment]
Merging it.
FYI @ticoann @vlimant @jenimal , in general it touches only RelVal directory, besides these
reqMgrClient.py
resubmit.py
setDatasetStatusDBS3.py
utils.py

**Comment by vlimant** [comment]
isnt't there a duplicate of makeReplicaRequest in the changes ?

**Comment by AndrewLevin** [comment]
yes, I guess we can remove the second one?

**Comment by vlimant** [comment]
yes, otherwise it's shadowing the first one

**Comment by AndrewLevin** [comment]
https://github.com/CMSCompOps/WmAgentScripts/pull/130

**Pull request merged**
