### PR TITLE
htmlor code with legacy mistakes

### PR DESCRIPTION
**Pull request by sharad1126**
Fixes errors in htmlor logs:
```
sort: cannot read: 6: No such file or directory
grep: write error: Broken pipe
```

#### Status
tested

#### Description
htmlor module logs shows errors due to some mistakes in code. 

#### Is it backward compatible (if not, which system it affects?)
NO

#### Related PRs
#489 

#### External dependencies / deployment changes
sort -f

#### Mention people to look at PRs
@z4027163

### CODE REVIEW

**Comment by vlimant** [comment]
interesting. you actually want "-k 6" instead of "-f 6"

**Comment by sharad1126** [comment]
thanks @vlimant will make the changes

**Comment by sharad1126** [comment]
@vlimant can you also please check from where is the following line coming in the logs and what needs to be done?
```
The dotted field 'vocms0815.cern.ch' in 'data.Negotiation.vocms0815.cern.ch' is not valid for storage.
```

**Comment by vlimant** [comment]
this line is coming from https://github.com/CMSCompOps/WmAgentScripts/commit/ae818b12409fdcf54174bee9c3707d948355a93c#diff-04d2c9518498da64bfa9db44c6211645

where documents are cached in mongodb. When the key has a "." mongodb rejects it and it reverts to using file based caching (small fraction of everything cached).

the way around it is to find an efficient/transparent way of doing replace(".","___dot___") (THAT actually might just be the solution )

**Comment by vlimant** [comment]
actually, now remembering better, this is coming from "." nested in the fields of the json being pushed to mongo https://github.com/CMSCompOps/WmAgentScripts/commit/bdc25648cac6c61c1605edc09180006e3381ada2 will not solve it. the error is harmless, and you probably have better to do

**Comment by sharad1126** [comment]
thanks for the quick responses. I will merge this PR for now. Thanks again.

**Pull request merged**
