### PR TITLE
Remove deprecated reqmgr param; clean reqmgr2 translated assignment p…

### PR DESCRIPTION
**Pull request by amaltaro**
…arams
I also fixed a couple of errors reported by pylint.
There is one more on `mc/mcassign.py`, but since I don't even know whether it's still used, I left it as it is
`E:952,137: Undefined variable 'events_per_lumi' (undefined-variable)`

Anyone, please review. It's not tested

### CODE REVIEW

**Comment by amaltaro** [comment]
@AndrewLevin since you are currently the main ReqMgr2 user, can you test this PR please?

**Comment by AndrewLevin** [comment]
yes, I will do it next week

**Comment by AndrewLevin** [comment]
ok, I applied the changes, if you don't hear from me, then you can assume there is no problem with them

**Comment by amaltaro** [comment]
@AndrewLevin is it working fine for you? If so, can someone merge it(?)

**Pull request merged**
